[phases.setup]
nixPkgs = ["ffmpeg", "python311", "gcc", "pkg-config", "libpq", "netcat-openbsd", "curl", "unzip"]

[phases.build]
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[phases.start]
cmd = "/entrypoint.sh"